// packages/react-animator/src/Animator/Animator.ts
import {
  type ReactElement,
  type ReactNode,
  type ForwardedRef,
  type DependencyList,
  createElement,
  useMemo,
  useContext,
  useRef,
  useEffect,
  useState
} from 'react'

import {
  type AnimatorNode,
  type AnimatorSettingsPartial,
  type AnimatorInterface,
  ANIMATOR_STATES as STATES,
  ANIMATOR_ACTIONS as ACTIONS,
  createAnimatorSystem
} from '@arwes-amir/animator'
import { AnimatorContext } from '../internal/AnimatorContext/index.js'
import { AnimatorGeneralContext } from '../internal/AnimatorGeneralContext/index.js'

interface AnimatorProps extends AnimatorSettingsPartial {
  root?: boolean
  disabled?: boolean
  dismissed?: boolean
  unmountOnExited?: boolean
  unmountOnEntered?: boolean
  unmountOnDisabled?: boolean
  refreshOn?: DependencyList
  nodeRef?: ForwardedRef<AnimatorNode>
  children?: ReactNode
}

const setNodeRefValue = (
  nodeRef: ForwardedRef<AnimatorNode> | undefined,
  node: AnimatorNode | null
): void => {
  if (typeof nodeRef === 'function') {
    nodeRef(node)
  } else if (nodeRef) {
    nodeRef.current = node
  }
}

const Animator = (props: AnimatorProps): ReactElement => {
  // It is responsibility of the <Animator> to register, setup, update, and unregister
  // the new node every time there is a change in it, since they happen on UI events.

  const {
    root,
    disabled,
    dismissed,
    unmountOnExited,
    unmountOnEntered,
    unmountOnDisabled,
    refreshOn,
    nodeRef,
    children,
    ...settings
  } = props

  const parentAnimatorInterface = useContext(AnimatorContext)
  const animatorGeneralInterface = useContext(AnimatorGeneralContext)

  const settingsRef = useRef<AnimatorSettingsPartial>(settings)
  const prevAnimatorRef = useRef<AnimatorInterface | undefined>(undefined)
  const isMountedRef = useRef<boolean>(true)

  settingsRef.current = settings

  const animatorGeneralSettings = animatorGeneralInterface?.getSettings()
  const isRoot = !!root || !parentAnimatorInterface
  const isDismissed = dismissed !== undefined ? !!dismissed : !!animatorGeneralSettings?.dismissed
  const isDisabled = disabled !== undefined ? !!disabled : !!animatorGeneralSettings?.disabled

  const animatorInterface: undefined | AnimatorInterface = useMemo(() => {
    if (prevAnimatorRef.current) {
      prevAnimatorRef.current.system.unregister(prevAnimatorRef.current.node)
    }

    if (isDismissed) {
      setNodeRefValue(nodeRef, null)
      return parentAnimatorInterface
    }

    if (isDisabled) {
      setNodeRefValue(nodeRef, null)
      return undefined
    }

    const system = isRoot ? createAnimatorSystem() : parentAnimatorInterface.system

    const getSettings = (): AnimatorSettingsPartial => {
      const animatorGeneralSettings = animatorGeneralInterface?.getSettings()

      const duration = {
        ...animatorGeneralSettings?.duration,
        ...settingsRef.current.duration
      }

      return {
        ...animatorGeneralSettings,
        ...settingsRef.current,
        duration
      }
    }

    const node = isRoot
      ? system.register(undefined, { getSettings })
      : system.register(parentAnimatorInterface.node, { getSettings })

    setNodeRefValue(nodeRef, node)

    return Object.freeze({ system, node })
  }, [parentAnimatorInterface, isRoot, isDisabled, isDismissed])

  prevAnimatorRef.current = animatorInterface

  const [isEnabledToUnmount, setIsEnabledToUnmount] = useState<boolean | undefined>(
    () =>
      (unmountOnExited && animatorInterface?.node.state === STATES.exited) ||
      (unmountOnEntered && animatorInterface?.node.state === STATES.entered) ||
      (unmountOnDisabled && isDisabled)
  )

  useEffect(() => {
    return () => {
      isMountedRef.current = false

      if (prevAnimatorRef.current) {
        prevAnimatorRef.current.system.unregister(prevAnimatorRef.current.node)
      }
    }
  }, [])

  // Setup on mounted and in case animator is disabled and then re-enabled,
  // trigger the setup once is created again.
  useEffect(() => {
    if (!animatorInterface) {
      return
    }

    queueMicrotask(() => {
      if (!isMountedRef.current) {
        return
      }
      animatorInterface.node.send(ACTIONS.setup)
    })
  }, [!!animatorInterface])

  // Trigger updates on animator only after first render, since in the first render
  // the setup event would take care of the initial data procedore.
  const isFirstRender1Ref = useRef<boolean>(true)
  useEffect(() => {
    if (isFirstRender1Ref.current) {
      isFirstRender1Ref.current = false
      return
    }

    if (!animatorInterface) {
      return
    }

    queueMicrotask(() => {
      if (!isMountedRef.current) {
        return
      }
      animatorInterface.node.send(ACTIONS.update)
    })
  }, [settings.active, settings.manager, settings.merge, settings.combine])

  useEffect(() => {
    if (animatorInterface) {
      const cancelSubscription = animatorInterface.node.subscribe((node) => {
        setIsEnabledToUnmount(
          (unmountOnExited && node.state === STATES.exited) ||
            (unmountOnEntered && node.state === STATES.entered)
        )
      })
      return () => cancelSubscription()
    } else {
      setIsEnabledToUnmount(unmountOnDisabled)
    }
  }, [animatorInterface, unmountOnExited, unmountOnEntered, unmountOnDisabled])

  const isFirstRender2Ref = useRef<boolean>(true)
  useEffect(() => {
    if (isFirstRender2Ref.current) {
      isFirstRender2Ref.current = false
      return
    }

    if (animatorInterface) {
      queueMicrotask(() => {
        if (!isMountedRef.current) {
          return
        }
        animatorInterface.node.send(ACTIONS.refresh)
      })
    }
  }, refreshOn ?? [])

  return createElement(
    AnimatorContext.Provider,
    { value: animatorInterface },
    isEnabledToUnmount ? null : children
  )
}

export type { AnimatorProps }
export { Animator }

// packages/solid-animator/src/Animator/Animator.tsx
// TODO: Compose settings condition.
// TODO: Compose settings onTransition.
// TODO: Add support for refresh.
// TODO: Add support for prop unmountOnExited.
// TODO: Add support for prop unmountOnEntered.
// TODO: Add support for prop unmountOnDisabled.
// TODO: Add support for prop nodeRef.

import { type Component, createMemo, createEffect, onCleanup } from 'solid-js'
import { filterProps } from '@arwes-amir/tools'
import {
  type AnimatorInterface,
  type AnimatorSettingsPartial,
  createAnimatorSystem
} from '@arwes-amir/animator'

import { AnimatorContext } from '../internal/AnimatorContext.js'
import { useGetAnimator } from '../useGetAnimator/index.js'
import { type ReactElement } from 'react'

interface AnimatorProps extends AnimatorSettingsPartial {
  root?: boolean
  disabled?: boolean
  dismissed?: boolean
  children?: ReactElement
}

const Animator: Component<AnimatorProps> = (props) => {
  const getParentAnimatorInterface = useGetAnimator()
  const parentAnimatorInterface = getParentAnimatorInterface?.()

  const settingsComponentRef: { current: AnimatorSettingsPartial } = { current: {} }
  const settingsDynamicRef: { current: AnimatorSettingsPartial | null } = { current: null }

  const getParentInterface = createMemo<AnimatorInterface | undefined>(() =>
    props.root ? undefined : parentAnimatorInterface
  )
  const getIsDisabled = createMemo<boolean>(() => !!props.disabled)
  const getIsDismissed = createMemo<boolean>(() => !!props.dismissed)

  createMemo(() => {
    settingsComponentRef.current = {
      active: props.active,
      duration: props.duration,
      manager: props.manager,
      merge: props.merge,
      combine: props.combine,
      initialState: props.initialState,
      condition: props.condition,
      onTransition: props.onTransition
    }
  })

  const getAnimatorInterface = createMemo<AnimatorInterface | undefined>(
    (prevAnimatorInterface) => {
      const parentInterface = getParentInterface()
      const isDisabled = getIsDisabled()
      const isDismissed = getIsDismissed()

      if (isDisabled) {
        if (prevAnimatorInterface) {
          prevAnimatorInterface.system.unregister(prevAnimatorInterface.node)
        }

        return undefined
      }

      if (isDismissed) {
        if (prevAnimatorInterface) {
          prevAnimatorInterface.system.unregister(prevAnimatorInterface.node)
        }

        return parentInterface
      }

      if (prevAnimatorInterface) {
        prevAnimatorInterface.system.unregister(prevAnimatorInterface.node)
      }

      const getSettings = (): AnimatorSettingsPartial => {
        return {
          ...filterProps(settingsComponentRef.current),
          ...(settingsDynamicRef.current ? filterProps(settingsDynamicRef.current) : null),
          duration: {
            ...(settingsComponentRef.current.duration
              ? filterProps(settingsComponentRef.current.duration)
              : null),
            ...(settingsDynamicRef.current?.duration
              ? filterProps(settingsDynamicRef.current?.duration)
              : null)
          }
        }
      }

      const system = parentInterface ? parentInterface.system : createAnimatorSystem()
      const parentNode = parentInterface ? parentInterface.node : undefined
      const node = system.register(parentNode, { getSettings })

      return Object.freeze({ system, node })
    }
  )

  createEffect(() => {
    const animatorInterface = getAnimatorInterface()

    if (animatorInterface) {
      queueMicrotask(() => {
        animatorInterface.node.send('setup')
      })
    }
  })

  createEffect(() => {
    void props.root
    void props.disabled
    void props.dismissed
    void props.active
    void props.combine
    void props.merge
    void props.manager

    const animatorInterface = getAnimatorInterface()

    if (animatorInterface) {
      queueMicrotask(() => {
        animatorInterface.node.send('update')
      })
    }
  })

  onCleanup(() => {
    const animatorInterface = getAnimatorInterface()

    if (animatorInterface) {
      animatorInterface.system.unregister(animatorInterface.node)
    }
  })

  return (
    <AnimatorContext.Provider value={getAnimatorInterface}>
      {props.children}
    </AnimatorContext.Provider>
  )
}

export type { AnimatorProps }
export { Animator }
